---
- name: File Module
  hosts: all

  tasks:
  - name: Creating a file
    file:
      path: /tmp/newfile.txt
      state: touch
      owner: tushar
      group: tushar
      mode: u=rwx,g=rw,o=r

  - name: Creating a directory
    file:
      path: /tmp/myfolder
      state: directory
    
  - name: Deleting a file
    file:
      path: /tmp/newfile.txt
      state: absent

  - name: Deleting a directory
    file:
      path: /tmp/myfolder
      state: absent