---

- name: Installing httpd
  hosts: all

  tasks:
  - name: Install httpd on RedHat
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"


  - name: Install apache2 on Ubuntu
    apt:  
      name: apache2
      state: present
    when: ansible_os_family == "Ubuntu"
