---
# tasks file for fwd_service
- name: Enable a service in firewalld
  firewalld:
    service: http
    state: enabled
    permanent: true
  becomes: true
  when: ansible_os_family == "RedHat"
  notify: Reload Firewall
