---
# tasks file for httpd_setup
- name: Install Httpd
  yum:
    name: "{{ httpd_package_name }}"    #variable is in vars folder
    state: present
  
  become: true

- name: Place Custom HTML File
  copy:
    src: index.html       #place the file in fiels folder and just provide the name
    dest: /var/www/html/index.html
  become: true

- name: Start the service
  service: 
    name: httpd
    state: started
    enabled: yes
  become: true  
